version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "3001"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
