name: WebPageTest Performance Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  wpt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (jq, bc)
        run: sudo apt-get update && sudo apt-get install -y jq bc

      - name: Run WebPageTest script
        env:
          # Use GitHub Actions secret for token in production!
          CATCHPOINT_TOKEN: ${{ secrets.CATCHPOINT_TOKEN }}
        run: |
          chmod +x .github/workflows/run_wpt.sh
          .github/workflows/run_wpt.sh